"""L5 - CIR -> markdown renderer.

Deterministic: the same CIR always renders to byte-identical markdown.
Frontmatter carries source provenance so the mirror is self-describing.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone

from doc_backbone.cir import CIR, Block, BlockKind

_FOOTER = "<!-- generated by doc-backbone v0 - do not edit; PDF is source of truth -->\n"


def _frontmatter(cir: CIR, parsed_utc: str) -> str:
    lines = [
        "---",
        f"source_hash: {cir.source_hash}",
        f"source_path: {cir.source_path}",
        f"doc_type: {cir.doc_type}",
        f"pages: {cir.pages}",
        f"extractor: {cir.extractor}",
        f"extractor_version: {cir.extractor_version}",
        f"parsed_utc: {parsed_utc}",
        "---",
        "",
    ]
    return "\n".join(lines)


def _render_block(b: Block) -> str:
    if b.kind == BlockKind.HEADING:
        level = max(1, min(6, b.level or 2))
        return f"{'#' * level} {b.text or ''}".rstrip()
    if b.kind == BlockKind.PARAGRAPH:
        return (b.text or "").rstrip()
    if b.kind == BlockKind.LIST:
        return f"- {b.text or ''}".rstrip()
    if b.kind == BlockKind.FOOTNOTE:
        return f"> {b.text or ''}".rstrip()
    if b.kind == BlockKind.TABLE and b.table:
        rows = b.table
        header = "| " + " | ".join(rows[0]) + " |"
        sep = "| " + " | ".join("---" for _ in rows[0]) + " |"
        body = "\n".join("| " + " | ".join(r) + " |" for r in rows[1:])
        return "\n".join([header, sep, body]) if body else "\n".join([header, sep])
    if b.kind == BlockKind.FIGURE:
        caption = b.text or "(figure)"
        return f"![{caption}]()"
    return ""


def render(cir: CIR, *, parsed_utc: str | None = None) -> str:
    """Render a CIR to markdown. Pass `parsed_utc` to pin the timestamp
    (tests rely on this for determinism)."""
    if parsed_utc is None:
        parsed_utc = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    parts: list[str] = [_frontmatter(cir, parsed_utc)]

    current_page = 0
    page_buffer: list[str] = []

    def flush_page() -> None:
        if current_page == 0:
            return
        parts.append(f"## Page {current_page}\n")
        if page_buffer:
            parts.append("\n\n".join(page_buffer) + "\n")
        else:
            parts.append("_(no extractable text)_\n")

    for b in cir.blocks:
        if b.kind == BlockKind.PAGE_BREAK:
            flush_page()
            page_buffer = []
            current_page = 0
            continue
        if b.page != current_page:
            flush_page()
            page_buffer = []
            current_page = b.page
        rendered = _render_block(b)
        if rendered:
            page_buffer.append(rendered)
    flush_page()

    parts.append("\n" + _FOOTER)
    return "\n".join(parts)


def cir_json_bytes(cir: CIR) -> bytes:
    """Serialize CIR to canonical JSON bytes (stable key order)."""
    return json.dumps(cir.to_dict(), sort_keys=True, indent=2, ensure_ascii=False).encode("utf-8")


def cir_content_hash(cir: CIR) -> str:
    return hashlib.sha256(cir_json_bytes(cir)).hexdigest()
